language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"


env:
  - TOX_VERSION="tox>=3.0,<3.1"
  - TOX_VERSION="tox>=3.1,<3.2"

install:
  - pip install ${TOX_VERSION} tox-travis codecov

script:
  - tox

after_success:
  - codecov
